version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container-name: ovisr/praxis-ladar-website
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
