import "@/devlink/global.css";
import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
// import "./globals.css";
import {
  DevLinkProvider,
  Menu,
  GlobalStyles,
  MainLogo,
  Footer,
  FooterServiceLink,
} from "@/devlink";

import servicesArray from "@/app/(website)/data/services";
import NavWrapper from "./components/NavWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const servicesListMarkup = servicesArray.map((service, key) => {
    return (
      <FooterServiceLink
        key={key}
        link={{ href: `/behandlung/${service.Slug}` }}
        text={service.Name}
      />
    );
  });

  return (
    <html lang="en">
      <Script src="https://dr-flex.de/embed.js?medicalPracticeId=53337" />
      <body className={inter.className}>
        <DevLinkProvider>
          <MainLogo />
          <NavWrapper />
          <Menu />
          <GlobalStyles />
          <div className="main-wrapper">{children}</div>
          <Footer servicesSlot={servicesListMarkup} />
        </DevLinkProvider>
      </body>
    </html>
  );
}
